### ISSUE TITLE
旧版资源下载不了

### ISSUE THREAD

**Issue by wuyou-123** [577fkj/GenshinProxy#54]
下载不了资源，提示要下载新版安装包

**Comment by ajjdbdishwbsi** [comment]
大哥啊能不能快点更新啊，都有魔改的genshinproxy给genshin3.2用了啊

**Comment by 112233rty** [comment]
……



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月04日 02:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [577fkj/GenshinProxy] 旧版资源下载不了 (Issue #54) |

下载不了资源，提示要下载新版安装包

**Comment by 112233rty** [comment]
这



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月22日 16:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [577fkj/GenshinProxy] 旧版资源下载不了 (Issue #54) |

大哥啊能不能快点更新啊，都有魔改的genshinproxy给genshin3.2用了啊

**Comment by 577fkj** [comment]
> 这 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年11月22日 16:01 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | Re: [577fkj/GenshinProxy] 旧版资源下载不了 (Issue #54) | 大哥啊能不能快点更新啊，都有魔改的genshinproxy给genshin3.2用了啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

?

**Comment by 112233rty** [comment]
别催了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月02日 22:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [577fkj/GenshinProxy] 旧版资源下载不了 (Issue #54) |

这 | | @.*** | | @.*** |
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年11月22日 16:01 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [577fkj/GenshinProxy] 旧版资源下载不了 (Issue #54) | 大哥啊能不能快点更新啊，都有魔改的genshinproxy给genshin3.2用了啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

?
